$env:BRAVE_SEARCH_KEY="YOUR_BRAVE_KEY"
$env:TERMS_SEARCH_PROVIDER="brave"

# Optional search limits
$env:TERMS_SEARCH_MAX_QUERIES="2"
$env:TERMS_SEARCH_MAX_RESULTS="5"
$env:TERMS_SEARCH_TIMEOUT_SEC="6"
